name:                hmigrator
version:             0.0.0.2
github:              "synaps13/hmigrator"
license:             BSD-3-Clause
author:              "Rahimgulov Rustam"
maintainer:          "rahimgulov.rustam@gmail.com"
copyright:           "2024 Rahimgulov Rustam"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Java Flyway inspired database migration tool and library
category:            database

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/synaps13/hmigrator#readme>

dependencies:
- base >= 4.7 && < 5
- directory >= 1.3
- filepath >= 1.4
- text >= 2.0
- hasql >= 1.6
- murmur-hash >= 0.1
- bytestring >= 0.11

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hmigrator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hmigrator

tests:
  hmigrator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hmigrator
    - hspec >= 2.4
    - QuickCheck >= 2.14
